### ISSUE TITLE
Players Pending

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#833]
Je ne parviens plus à valider un "pending player"
Pourriez-vous vérifier le pourquoi svp?

**Comment by pzia** [comment]
hello @Phille,
- sur testing ou sur la prod ?
- c'est dans quel cas que tu as besoin de validé un pending ?
- quel est le message d'erreur ?

(connexion à quelques ko/s pour quelques jours, donc ne pas s'attendre à
une réaction immédiate...)

2015-05-08 19:43 GMT+02:00 Phille notifications@github.com:

**Comment by Phille** [comment]
- Sur N2
- Pour valider un nouveau joueur qui se plaint ne pouvoir se connecter à VLM (n'a pas lu ou reçu le mail de confirmation) ... voici un exemple d'une demande: "Creo que he abierto mi cuenta con obras@sipta.com y mi contraseña ba35b785, y me da fallo al entrar.
  No se solucionarlo"
- pas de message d'erreur, mais il ne figure pas dans les players validés

**Comment by sbsrouteur** [comment]
ca en est ou ton pb de player pending?

**Comment by Phille** [comment]
Nulle part … je crois ;)

Avez-vous fait qq chose?

**Comment by sbsrouteur** [comment]
non moi j'ai rien fait, et je ne pense pas que @pzia non plus. Donc on va dire qu'on a eu un cas bizarre qui ne se reproduira plus et clore?

**Comment by Phille** [comment]
Pourriez-vous ajouter la mention "N'oubliez pas de vérifier votre boîte SPAM" dans le texte qui demande au joueur de confirmer son inscription? Beaucoup de joueurs ne parviennent pas à s'inscrire à VLM! Jetez un coup d'oeil à la liste des "players pending" ... ya 6 pages (beaucoup de doublons...donc des gars qui insistent)! http://v-l-m.org/admin/players_pending.php

**Comment by maitaivw** [comment]
Ce pourrait-il que ca cache une problème plus grave, style mail non envoyé ou pire v-l-m blacklisté quelque part?

**Comment by Phille** [comment]
le mail est envoyé, j'ai fait un essai, mais je l'ai trouvé dans ma boîte SPAM de Gmail! :(

**Comment by maitaivw** [comment]
Les causes peuvent être nombreuses:

http://superuser.com/questions/351817/why-does-gmail-think-mail-my-server-sends-is-a-spam

**Comment by Phille** [comment]
François va s'en occuper ... et va chercher si et où nous sommes blacklisté..
nous avons 282 players "pending", c'est pas normal et en plus ça nous prive de pas mal de nouveaux joueurs :(
http://v-l-m.org/admin/players_pending.php

**Comment by maitaivw** [comment]
Ca c'est une bonne nouvelle... Espérons...

**Comment by farangfrog** [comment]
Depuis 2015, le nombre de players pending n'a fait que croitre... Et très rares à ma connaissance sont ceux qui nous contacte en cas de non réception du mail de confirmation. Un cas aujourd'hui, avec un joueur ayant essayé de s'inscrire avec 2 comptes hotmail.fr et pour lesquels aucun message de confirmation n'a été reçu (il est allé voir dans les spams).

Est ce qu'il y a eu des progrès à ce sujet ?

**Comment by sbsrouteur** [comment]
Bon voila pourquoi :

mail.info:Oct  2 18:24:28 neptune2 postfix/smtp[20174]: 3C17C12CD: to=<
sergewolkowicz@hotmail.com>, relay=mx1.hotmail.com[65.55.37.72]:25,
delay=0.66, delays=0.01/0/0.49/0.16, dsn=5.0.0, status=bounced (host
mx1.hotmail.com[65.55.37.72] said: 550 SC-001 (COL004-MC1F15)
Unfortunately, messages from 212.129.54.94 weren't sent. Please contact
your Internet service provider since part of their network is on our block
list. You can also refer your provider to
http://mail.live.com/mail/troubleshooting.aspx#errors. (in reply to MAIL
FROM command))
mail.info:Oct  2 18:27:02 neptune2 postfix/smtp[20473]: 652D31310: to=<
sergewolkowicz@hotmail.com>, relay=mx2.hotmail.com[65.55.33.135]:25,
delay=0.65, delays=0.01/0/0.48/0.16, dsn=5.0.0, status=bounced (host
mx2.hotmail.com[65.55.33.135] said: 550 SC-001 (COL004-MC6F4)
Unfortunately, messages from 212.129.54.94 weren't sent. Please contact
your Internet service provider since part of their network is on our block
list. You can also refer your provider to
http://mail.live.com/mail/troubleshooting.aspx#errors. (in reply to MAIL
FROM command))

Le service de e-reputation de live/microsoft/hotmail....

Je vais voir si je peux gérer ça. Mais comme ce n'est pas moi qui possède
le domaine, je pense que ça sera à FM de devoir gérer.

++

2016-10-02 20:28 GMT+02:00 farangfrog notifications@github.com:

**Comment by sbsrouteur** [comment]
Est-ce que VLM est inscrit dans le program anti-junk MS?

https://postmaster.live.com/snds/JMRP.aspx?wa=wsignin1.0

++

**Comment by sbsrouteur** [comment]
Bon FM a ajusté ce qu'il faut en attendant de "déblacklister" neptune.

Est-ce que quelqu'un a une adresse hotmail ou outlook.com pour tester?

++

**Comment by farangfrog** [comment]
J'ai une adresse hotmail.fr. Je viens de tester, le message de confirmation arrive dans les spams, mais il arrive

**Comment by farangfrog** [comment]
Pour l'instant, lorsque le site envoie le message, on affiche seulement :

"Un courriel vient de vous être envoyé. Cliquez sur le lien reçu pour valider votre demande."

AMA, ce serait bien de suggérer de vérifier le dossier spam si le lien n'est pas reçu, et de contacter le comité (vlm@...) si il n'est pas dans le dossier spam.

**Comment by farangfrog** [comment]
Je ne sais pas si c'est lié à cela, mais je n'ai pas reçu les mails annonçant les vainqueurs de la TDU #19, qui sont pourtant arrivés il y a plus de 2 heures. Adresse gmail.com. Sur twitter, c'est passé par contre.

**Comment by sbsrouteur** [comment]
on peut clore ces soucis de mail ?

**Comment by farangfrog** [comment]
Je viens de tester sur une adresse @hotmail.fr. Le message de demande de validation est bien arrivé, mais dans le dossier spam. Je réitère donc la suggestion que le message qui s'affiche quand on demande la création du compte ne soit plus :

`Un courriel vient de vous être envoyé. Cliquez sur le lien reçu pour valider votre demande.`

mais :

`Un courriel vient de vous être envoyé. Cliquez sur le lien reçu pour valider votre demande. Vérifiez votre dossier spam si vous ne voyez pas le message. En cas de difficulté, contactez vlm@virtual-winds.org`

ou quelque chose comme ça...

**Comment by farangfrog** [comment]
cf #994 

(sbs : merged 576554de8342ec05abeb58c327cc0e530fe1babd)

**Comment by sbsrouteur** [comment]
fixed 1866c8056c1bfd0e3c04a7252e5cd68071fb76a6
